# Generated by Django 2.2.5 on 2019-09-24 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universo', '0001_initial'),
        ('viloes', '0002_viloes_habilidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='viloes',
            name='universo_viloes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='universo_viloes', to='universo.Universo'),
            preserve_default=False,
        ),
    ]
