# Generated by Django 2.2.5 on 2019-09-24 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habilidade', '0001_initial'),
        ('herois', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='herois',
            name='habilidade_heroi',
            field=models.ManyToManyField(related_name='habilidade_heroi', to='habilidade.Habilidade'),
        ),
    ]
